import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/providers/theme-provider";
import { TRPCReactProvider } from "@/trpc/client";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Miscord",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider signInFallbackRedirectUrl="/" signUpFallbackRedirectUrl="/">
      <html lang="en" suppressHydrationWarning>
        <body className={`${font.className} dark:bg-[#303338]`}>
          <TRPCReactProvider>
            <ThemeProvider
              storageKey="miscord-theme"
              attribute="class"
              defaultTheme="dark"
            >
              <Toaster />
              {children}
            </ThemeProvider>
          </TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
